services:
  - type: web
    name: cet4-vocabulary-app
    runtime: node
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
